####
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"kennynet66@gmail.com",
  "password":"test12"
}


###
GET http://localhost:3000/auth/checkdetails
Content-Type: application/json
token: 