###  Create a  new product
POST http://localhost:3000/categories/new-category
Content-Type: application/json

{
    "categoryName": "Music"
}

### Fetch all categories
GET http://localhost:3000/categories/all-categories

### get a single category
GET http://localhost:3000/categories/0200a1e0-08ad-40e7-bfa8-61a958299bf9