###  Create a  new product
POST http://localhost:3000/categories/new-category
Content-Type: application/json

{
    "categoryName": "Music"
}

### Fetch all categories
GET http://localhost:3000/categories/all-categories

### get a single category
GET http://localhost:3000/categories/6dfe9ab8-30ed-4008-b904-43d534d2a4c9