### Create a new product
POST http://localhost:3000/products/new-product
Content-Type: application/json

{
    "productName": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    "descr": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    "productQuantity": 200,
    "productImage": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    "productCategory": "men's clothing",
    "productPrice": 109.95
}


### Get all products
GET http://localhost:3000/products/all-products

### Delete a product

DELETE http://localhost:3000/products/delete/0bd1f651-f463-4b35-82ff-4ce81afacde7

### Get a single product
GET http://localhost:3000/products/8db63923-d689-4231-94c7-6512abfb9b48

### Get category products
GET http://localhost:3000/products/category-products/aed2ae09-81b2-4532-ba16-421d498af6b3

### Update a product
PUT http://localhost:3000/products/update/8db63923-d689-4231-94c7-6512abfb9b48
Content-Type: application/json

{
    "productName": "Small Juice wrld t-shirt",
    "descr": "This is a descr",
    "productQuantity": 200,
    "productImage": "https://i.ebayimg.com/images/g/GJcAAOSwMb9is9wL/s-l1200.webp",
    "productCategory": "6dfe9ab8-30ed-4008-b904-43d534d2a4c9",
    "productPrice": 600
}