###Create User
POST http://localhost:3000/user
Content-Type: application/json

{
  "firstName": "kingangi",
  "lastName": "kingangi",
  "email": "kingangi@skiff.com",
  "password": "kingangi"
}

### Get Users
GET http://localhost:3000/user
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNDdmMjQ1OC1mZmM0LTRjZGYtODA1Yy04Zjg3YzNhZjM1ZTEiLCJmaXJzdE5hbWUiOiJLZW5lZHkiLCJsYXN0TmFtZSI6Ik1haW5hIiwiZW1haWwiOiJrZW5ueW5ldDY2QGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlzRGVsZXRlZCI6bnVsbCwiaWF0IjoxNzA5NzYxNDU4LCJleHAiOjE3MDk3OTc0NTh9.3zzs7gWwceLajIRy2dTh5nrJWMBfZ_xAdWiQ6eI6ItY

### Update User
PUT http://localhost:3000/user/update/:id
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "firstName": " ",
  "lastName": " ",
  "email": " ",
}

### Get One User
GET http://localhost:3000/user/:id
Authorization: Bearer YOUR_ACCESS_TOKEN

### Delete User
DELETE http://localhost:3000/user/delete/:id
Authorization: Bearer YOUR_ACCESS_TOKEN